# from django.core.exceptions import ValidationError


# class UserAlreadyExistsError(ValidationError):
#     def __init__(self, code=None, params=None) -> None:
#         message = "A user with this email already exists"
#         super().__init__(message=message, code=code, params=params)
